
help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: clean_logs  ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".mypy_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean_logs: ## Clean log dir
	rm -rf logs && mkdir logs

clean_data: ## Clean data dir
	rm -rf data && mkdir data

clean_checkpoints: ## Clean checkpoints dir
	rm -rf ckpts && mkdir ckpts && touch ckpts/.gitkeep

clean_cache: ## Clean cache dir
	rm -rf osmnx_cache

clean_outputs: ## Clean outputs dir
	rm -rf out && mkdir out
